/**
 * YOUR_GAME_NAME - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       YOUR_GAME_NAME
 *   Title ID:    0x00000000
 *   Base addr:   0x00010000
 *   Entry point: 0x00000000
 *   Code size:   ~??? KB (.text)
 *   Sections:    ?? (list them)
 *   Kernel imports: ??
 */

#include <windows.h>

int recomp_dispatch_init(void);           /* (recomp/gen/recomp_dispatch.c) */
#include <dbghelp.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

/* xboxrecomp runtime headers: the kernel replacement and the memory
 * layout (the game's own D3D, DirectSound and input are replaced in this
 * port, so none of the runtime's compatibility layers are linked) */
#include "kernel.h"
#include "xbox_memory_layout.h"
#include "buffy_settings.h"

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. The
 * host side then writes g_esp somewhere the generated code never reads, so the
 * guest starts with every register at zero and faults immediately, having
 * apparently ignored the setup that visibly ran. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
/* x87 and SSE state. Global for the same reason the volatile GPRs are: one
 * guest routine can lift to several C functions, so a value written in one
 * body is read in the next. Defined in xbox_memory_layout.c like the rest of
 * the register file. */
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_ENTRY_POINT   0x001287F6  /* XBE entry point VA */

/* The game dir is the D:\ root: it holds default.xbe and Buffy\Binary\...
 * Defaults to the folder the .exe lives in; BUFFY_GAME_DIR overrides it.
 * The saves are plain files in SaveData beside the .exe (buffy_saves.c); the
 * emulated console's own files (T:, Z:, the hard disk) go to XboxData. */
static char g_game_dir[MAX_PATH];
static char g_xbe_path[MAX_PATH];
static char g_save_dir[MAX_PATH];

static void resolve_game_paths(void)
{
    char exe_dir[MAX_PATH];
    const char *env = getenv("BUFFY_GAME_DIR");
    char *slash;

    GetModuleFileNameA(NULL, exe_dir, MAX_PATH);
    slash = strrchr(exe_dir, '\\');
    if (slash) *slash = '\0';

    strcpy_s(g_game_dir, MAX_PATH, (env && *env) ? env : exe_dir);
    sprintf_s(g_xbe_path, MAX_PATH, "%s\\default.xbe", g_game_dir);
    sprintf_s(g_save_dir, MAX_PATH, "%s\\XboxData", exe_dir);
    {
        void buffy_saves_init(const char *exe_dir, const char *game_dir);
        buffy_saves_init(exe_dir, g_game_dir);   /* (converts an older version's saves) */
    }
}

#define YOUR_GAME_XBE_PATH      g_xbe_path
#define YOUR_GAME_DIR           g_game_dir

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Recompiled entry point (generated by recomp pipeline) */
extern void mainCRTStartup_001287F6(void);
#define xbe_entry_point mainCRTStartup_001287F6

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
/* Name the guest function a fault happened in, and recover the call chain.
 *
 * Recompiled code faults as ordinary native code, so the exception record
 * carries a host RIP and nothing else -- there is no guest program counter to
 * report, and the host address changes every build. Two things recover the
 * guest view:
 *
 *   - every generated function is a real symbol in the image (sub_005A03C0
 *     and so on), so the linker's PDB already maps host address back to guest
 *     function. dbghelp turns an anonymous RIP into that name.
 *
 *   - every lifted call pushes its guest return address onto the guest stack
 *     before jumping, so the stack still holds the chain. Scanning up from esp
 *     for values inside the code sections recovers it.
 *
 * ponytail: the stack scan is a scan, not a frame walk -- these are FPO frames
 * with no reliable ebp chain, so there is nothing to walk. It over-reports,
 * since addresses from returned-from calls linger below esp, but naming the
 * guest function is the whole question at a fault.
 *
 * Requires linking dbghelp and keeping the .pdb beside the .exe.
 */
static void print_guest_context(void *rip)
{
#if defined(_WIN32) /* guard */
    /* SYMBOL_INFO is variable-length: the name is written past the struct, so
     * it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n",
                sym->Name, (unsigned long long)disp);

    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (return addresses, innermost first):\n");
        for (i = 0; i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
    }
#else
    (void)rip;
#endif
}

/* ── Write watchpoint (BUFFY_WATCH=0xVA) ─────────────────────────
 * Makes the guest page holding VA read-only; every write to that page faults,
 * writes that touch [VA, VA+16) are logged with the host function and guest
 * call stack, and the instruction is single-stepped with the page unprotected
 * before the protection is re-armed. For "who overwrote this" questions. */
static uint32_t g_watch_va;
static uint8_t *g_watch_page;
static int g_watch_hits;

static void watch_arm(void)
{
    DWORD old;
    VirtualProtect(g_watch_page, 0x1000, PAGE_READONLY, &old);
}

static void watch_init(void)
{
    const char *s = getenv("BUFFY_WATCH");
    if (!s)
        return;
    g_watch_va = (uint32_t)strtoul(s, NULL, 0);
    g_watch_page = (uint8_t *)(((uintptr_t)g_xbox_mem_offset + g_watch_va) & ~(uintptr_t)0xFFF);
    watch_arm();
    fprintf(stderr, "[WATCH] armed on 0x%08X\n", g_watch_va);
}

static void print_guest_context(void *rip);

static LONG watch_handle(PEXCEPTION_POINTERS ep)
{
#if defined(_WIN32) /* guard */
    PEXCEPTION_RECORD er = ep->ExceptionRecord;

    if (!g_watch_page)
        return EXCEPTION_CONTINUE_SEARCH;
    if (er->ExceptionCode == EXCEPTION_SINGLE_STEP) {
        watch_arm();
        return EXCEPTION_CONTINUE_EXECUTION;
    }
    if (er->ExceptionCode == EXCEPTION_ACCESS_VIOLATION && er->ExceptionInformation[0] == 1) {
        uint8_t *a = (uint8_t *)er->ExceptionInformation[1];
        if (a >= g_watch_page && a < g_watch_page + 0x1000) {
            uint32_t va = (uint32_t)((uintptr_t)a - (uintptr_t)g_xbox_mem_offset);
            DWORD old;
            if (va + 8 > g_watch_va && va < g_watch_va + 16 && g_watch_hits++ < 40) {
                fprintf(stderr, "[WATCH] write to 0x%08X (old %08X)\n", va,
                        *(uint32_t *)((uintptr_t)g_xbox_mem_offset + (va & ~3u)));
                print_guest_context((void *)ep->ContextRecord->Rip);
            }
            VirtualProtect(g_watch_page, 0x1000, PAGE_READWRITE, &old);
            ep->ContextRecord->EFlags |= 0x100;  /* trap flag: re-arm after one instruction */
            return EXCEPTION_CONTINUE_EXECUTION;
        }
    }
    return EXCEPTION_CONTINUE_SEARCH;
#else
    (void)ep;
    return EXCEPTION_CONTINUE_SEARCH;
#endif
}

/* Hex-dump guest memory around every register that points into mapped RAM.
 * Most bring-up crashes are a bad pointer read out of a structure, and the
 * structure is usually what one of the registers still points at. */
static void dump_guest_regs_memory(void)
{
    const char *names[] = { "eax", "ecx", "edx", "ebx", "esi", "edi", "esp" };
    uint32_t vals[] = { g_eax, g_ecx, g_edx, g_ebx, g_esi, g_edi, g_esp };
    int r, i;

    for (r = 0; r < 7; r++) {
        uint32_t base = (vals[r] & ~0xFu) - 0x20;
        if (vals[r] < 0x10000 || (vals[r] >= 0x04000000 && vals[r] < 0x80000000)
                || vals[r] >= 0x84000000)
            continue;
        fprintf(stderr, "  mem @%s=0x%08X:\n", names[r], vals[r]);
        for (i = 0; i < 0x60; i += 16) {
            const uint32_t *p = (const uint32_t *)((uintptr_t)g_xbox_mem_offset + base + i);
            fprintf(stderr, "    %08X: %08X %08X %08X %08X\n", base + i, p[0], p[1], p[2], p[3]);
        }
    }
}

/* The runtime's optional framebuffer window (for its software rasteriser)
 * and host video player (RECOMP_FMV_HOST) live in its xbox_video library,
 * which this port does not link: the game's window is the GPU layer's and
 * its movies play through buffy_movie.c. The kernel bridge's calls into
 * them land here. */
void xbox_FramebufferWindowSet(uint32_t fb_va, uint32_t pitch) { (void)fb_va; (void)pitch; }
void xbox_FramebufferWindowStart(void) {}
int  xbox_VideoPlayFile(const char *host_path) { (void)host_path; return 0; }
int  xbox_VideoIsPlaying(void) { return 0; }

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
#if defined(_WIN32) /* guard */
    {
        LONG w = watch_handle(ep);
        if (w != EXCEPTION_CONTINUE_SEARCH)
            return w;
    }
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));
        print_guest_context((void *)ep->ContextRecord->Rip);
        dump_guest_regs_memory();

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
#else
    (void)ep;
    return EXCEPTION_CONTINUE_SEARCH;
#endif
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    /* Started by a player (stdout/stderr on a console, or none at all):
     * send diagnostics to buffy_log.txt beside the exe, so a crash or an
     * unexpected exit leaves a record instead of vanishing with the window.
     * Test runs redirect the streams themselves and are left alone. */
#if defined(_WIN32) /* (Android: stderr goes to logcat, android_main.c) */
    {
        DWORD t = GetFileType(GetStdHandle(STD_ERROR_HANDLE));
        if (t == FILE_TYPE_CHAR || t == FILE_TYPE_UNKNOWN) {
            char path[MAX_PATH], *slash;
            GetModuleFileNameA(NULL, path, MAX_PATH);
            slash = strrchr(path, '\\');
            if (slash) {
                char prev[MAX_PATH];
                strcpy_s(slash + 1, MAX_PATH - (slash + 1 - path), "buffy_log.txt");
                /* the last run's log stays, as buffy_log_previous.txt: restarting
                 * after a freeze or crash must not wipe the one that says why */
                strcpy_s(prev, MAX_PATH, path);
                strcpy_s(prev + (slash + 1 - path), MAX_PATH - (slash + 1 - path), "buffy_log_previous.txt");
                MoveFileExA(path, prev, MOVEFILE_REPLACE_EXISTING);
                freopen(path, "w", stderr);
                strcpy_s(slash + 1, MAX_PATH - (slash + 1 - path), "buffy_out.txt");
                freopen(path, "w", stdout);
            }
        }
    }
#endif

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== Buffy the Vampire Slayer: Chaos Bleeds - Static Recompilation ===\n");
    {
        const char *buffy_platform_text(void);
        fprintf(stderr, "[PLATFORM] %s\n", buffy_platform_text());
        fprintf(stderr, "  [THREAD] %lu: game\n", GetCurrentThreadId());
    }
    /* The console's own folders (XboxData: T:, Z:, the hard disk) only when
     * the game writes something there -- normally never: saves are SaveData
     * (buffy_saves.c), and T: / U: are not linked (XapiSetupPerTitleDriveLetters). */
    if (!getenv("RECOMP_LAZY_DIRS"))
        _putenv("RECOMP_LAZY_DIRS=1");
    resolve_game_paths();
    {
        /* Is this executable the installed release's? Before anything else
         * starts (a window, the GPU), so the other release's executable can
         * run in its place (buffy_xbecheck.c). */
        int buffy_check_xbe_release(const uint8_t *d, size_t n, int *exit_code);
        void *xd = NULL;
        size_t xn = 0;
        int code;
        if (load_xbe(YOUR_GAME_XBE_PATH, &xd, &xn)) {
            int go_on = buffy_check_xbe_release((const uint8_t *)xd, xn, &code);
            free(xd);
            if (!go_on)
                return code;
        }
    }

    /* Audio: no emulated sound chip. DirectSound is replaced whole
     * (buffy_dsound.c: DirectSoundCreate, CommitDeferredSettings,
     * DownloadEffectsImage and every buffer call), so nothing reaches the
     * MCPX APU, the AC'97 codec or the DSP mailbox; the emulated APU and its
     * register traps (RECOMP_AC97_READY, RECOMP_APU_DSP_ACK) stay off. */
    /* GPU: none to emulate. The game draws through the native renderer
     * (buffy_native.c), and the Xbox D3D library runs in its own no-GPU mode
     * (D3D__NullHardware, set below): the pushbuffer it still writes is
     * retired at once, and nothing waits on GPU registers, fences or a
     * vertical blank (buffy_gpuwait.c). So no pushbuffer thread, no vblank
     * interrupt and no register thread. */
    _putenv("RECOMP_PB_EXEC=0");
    _putenv("RECOMP_VBLANK=0");
    _putenv("RECOMP_NV2A_ACK=0");
    /* Memory as a PC program has it: the game's 4 GB address space is one
     * block the system places (xbox_memory_layout.c), without the Xbox's
     * hardware aliases -- RAM repeated every 64 MB (the memory bus wrap) and
     * the GPU's tiled view of it at 0xF0000000. The game uses neither (the
     * story, co-op, movies and all three renderers run without them); set
     * RECOMP_NO_MIRRORS=0 / RECOMP_NO_TILED=0 to bring one back. */
    if (!getenv("RECOMP_NO_MIRRORS"))
        _putenv("RECOMP_NO_MIRRORS=1");
    if (!getenv("RECOMP_NO_TILED"))
        _putenv("RECOMP_NO_TILED=1");
    /* Nor the Xbox's other device blocks: the MCPX (audio, USB, network --
     * DirectSound, controllers and saves are answered above it) and the
     * BIOS flash. RECOMP_NO_MCPX=0 / RECOMP_NO_FLASH=0 bring one back. */
    if (!getenv("RECOMP_NO_MCPX"))
        _putenv("RECOMP_NO_MCPX=1");
    if (!getenv("RECOMP_NO_FLASH"))
        _putenv("RECOMP_NO_FLASH=1");
    /* RECOMP_USB (the OHCI/USB wire model) stays opt-in: controllers are
     * answered at the XAPI level in buffy_input.c. */
    /* The game window (presents the flipped surface). Test harnesses set
     * BUFFY_NO_WINDOW to stay headless. */
    /* The game window comes from the GPU layer (Vulkan or Direct3D 11). */
    buffy_settings_load();          /* resolution, vsync, fullscreen */
    {
        void buffy_debug_start(void);
        buffy_debug_start();        /* left stick / F12: bug report (buffy_debug.c) */
    }
    {
        int buffy_native_mode(void);
        buffy_native_mode();        /* native renderer: the device comes up now (buffy_native.c) */
    }
    {
        void buffy_mods_load(void);
        buffy_mods_load();          /* ticked mods overlay the game folder */
    }
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    /* Load symbols up front rather than from inside the handler: at fault
     * time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler prints no name. */
    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME);
    SymInitialize(GetCurrentProcess(), NULL, TRUE);
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    {
        void buffy_coop_memory_early(void);
        buffy_coop_memory_early();  /* story co-op: a 128 MB contiguous window */
    }
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);
    watch_init();
    /* The Xbox D3D library's own no-GPU mode, D3D__NullHardware (0x145030,
     * BSS): KickOff retires the pushbuffer at once instead of handing it to
     * a GPU (buffy_gpuwait.c). */
    *(volatile uint32_t *)((uintptr_t)g_xbox_mem_offset + 0x145030u) = 1;
    {
        void buffy_coop_memory_patch(void);
        buffy_coop_memory_patch();  /* ...and a bigger game heap in it */
    }

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, g_save_dir);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over the
     * whole function table -- roughly log2(n) branches on *every*
     * indirect call, which for a 45,000-function C++ title is about 16
     * every time the game goes through a vtable. Half-Life 2 spent most
     * of its static initialisation inside recomp_lookup for exactly this
     * reason, and it read as a hang.
     *
     * Optional by design: if the allocation fails the search still works,
     * so a failure is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    /* Arm the hang watchdog. Does nothing unless RECOMP_WATCHDOG_SECS is set,
     * and must be called from this thread -- the guest registers it samples are
     * thread-local, so it has to be handed the copies belonging to the thread
     * that runs guest code.
     *
     * Not optional boilerplate: without this call RECOMP_WATCHDOG_SECS is
     * silently inert, and the one diagnostic that tells a hang from slowness
     * does nothing while appearing to be set. */
    xbox_WatchdogStart();

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");
    fprintf(stderr, "[MAIN] game entry returned: esp=%08X eax=%08X\n", g_esp, g_eax);
    fflush(stderr);

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

#if defined(BUFFY_ANDROID)
/* Android: the game thread's entry (android_main.c). */
int buffy_game_main(void)
{
    return WinMain(NULL, NULL, (LPSTR)"", 0);
}
#else
/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
#endif

/* Microsecond clock for tools/probe.py probes. */
unsigned long long buffy_probe_us(void)
{
    static LARGE_INTEGER f;
    LARGE_INTEGER q;
    if (!f.QuadPart)
        QueryPerformanceFrequency(&f);
    static LARGE_INTEGER t0;
    QueryPerformanceCounter(&q);
    if (!t0.QuadPart) {
        /* Process start: the creation time, in the same clock. */
        FILETIME c, e, k, u, now;
        ULARGE_INTEGER a, b;
#if defined(_WIN32)
        GetProcessTimes(GetCurrentProcess(), &c, &e, &k, &u);
#else
        GetSystemTimeAsFileTime(&c);
#endif
        GetSystemTimeAsFileTime(&now);
        a.LowPart = c.dwLowDateTime; a.HighPart = c.dwHighDateTime;
        b.LowPart = now.dwLowDateTime; b.HighPart = now.dwHighDateTime;
        t0.QuadPart = q.QuadPart - (LONGLONG)((b.QuadPart - a.QuadPart) / 10 * (f.QuadPart / 1000000.0));
    }
    return (unsigned long long)((q.QuadPart - t0.QuadPart) * 1000000.0 / (double)f.QuadPart);  /* since start */
}
